### ISSUE TITLE
Add analysis code for article codes.

### ISSUE THREAD

**Issue by hh1985** [xbiome/StrainPanDA#13]
add code into the `example` subfolder.

**Comment by lch14forever** [comment]
added [example/kong_et_al_IBD_FMT/](https://github.com/xbiome/StrainPanDA/tree/main/example/kong_et_al_IBD_FMT/)

**Comment by yuxiangtan** [comment]
Filled contents in example and reorganized

**Comment by lch14forever** [comment]
Assume fixed
