### ISSUE TITLE
bug report: Error in rowSums(mat) : 'x' must be an array of at least two dimensions

### ISSUE THREAD

**Issue by fgnddddd** [xbiome/StrainPanDA#19]
<img width="541" alt="image" src="https://user-images.githubusercontent.com/99473225/169469033-06278681-bb49-41c4-8a56-28ba289ad2eb.png">

测试样品与之前相同
`nextflow run /share//home/zhangzhikuan/zhangzhikuan_hpc/gitlab/xstrain/StrainPanDA/main.nf -profile hpc --path /share/home/zhangzhikuan/zhangzhikuan_hpc/pipeline_test/xstrain/data --ref_path /share/work/runtime/databases/xstrain/panphlan_ref20200`
exitcode = 1

**Comment by lch14forever** [comment]
Assume fixed. Please reopen if it doesn't work.
