### ISSUE TITLE
安装错误

### ISSUE THREAD

**Issue by yzzhang68** [xbiome/StrainPanDA#20]
下载后，运行tar -czf strainpandar.tar.gz src/strainpandar后，运行R CMD INSTALL strainpandar.tar.gz，提示错误
ERROR: cannot extract package from ‘strainpandar.tar.gz’

R为conda环境安装，已用conda安装dplyr, foreach, MASS, NMF

**Comment by lch14forever** [comment]
Apologies for the issue. 

I have updated the document (Commit 666b132, note on the added dependencies `pracma` and `vegan`):

install [R](https://www.r-project.org/) and [strainpandar](https://github.com/xbiome/StrainPanDA/blob/main/src/strainpandar): decomposing pangenome into strains
Install required packages dplyr, foreach, MASS, NMF, pracma, vegan

```sh
git clone https://github.com/xbiome/StrainPanDA.git
cd StrainPanDA/src
tar -czf strainpandar.tar.gz strainpandar
R CMD INSTALL strainpandar.tar.gz
```

**Comment by hh1985** [comment]
@yzzhang68

**Comment by hh1985** [comment]
@yzzhang68 你好，请问安装问题是否已经解决呢？

**Comment by yzzhang68** [comment]
你好！在安装pracma和vegan后执行R CMD INSTALL命令时仍然显示同样错误。ERROR: cannot extract package from ‘strainpandar.tar.gz’。 请问是否可以提供一个可以执行的tar.gz包供下载？谢谢！

**Comment by hh1985** [comment]
@lch14forever 能提供一个打包好的tar.gz么？

**Comment by lch14forever** [comment]
@yzzhang68 
We will figure out a place to host the tarball that is convenient to download.

In the meantime, could you help confirm your working directory is `StrainPanDA/src`?
> **Note** the following changes in the installation instructions
> cd **StrainPanDA/src**
> tar -czf **strainpandar.tar.gz** strainpandar

**Comment by yzzhang68** [comment]
I saw the readme file has been updated. Previously I followed the command in the old readme file "tar -czf strainpandar.tar.gz src/strainpandar" and got the error. Now I tried the new command, it works, and the package has been installed successfully. Thanks.

**Comment by lch14forever** [comment]
Consider fixed.
