### ISSUE TITLE
merge issue on PanPhlan output

### ISSUE THREAD

**Issue by yuxiangtan** [xbiome/StrainPanDA#29]
> > 是的，我的docker镜像没有安装成功。成功安装之后还是遇到了一些问题 1.如下报错信息（我认为我解决了这个问题）： [5b/e15e17] process > panphlanMap (Gutmock_R|Escherichia-coli-202009) [100%] 21 of 21 ✔ [97/688bf5] process > mergeProfile (Escherichia-coli-202009) [100%] 1 of 1, failed: 1 ✘ [- ] process > runStrainPanDAR - [- ] process > runMinPath - Execution cancelled -- Finishing pending tasks before exit WARN: Graphviz is required to render the execution DAG in the given format -- See http://www.graphviz.org for more info. Error executing process > 'mergeProfile (Escherichia-coli-202009)'
> > Caused by: Process `mergeProfile (Escherichia-coli-202009)` terminated with an error exit status (126)
> > Command executed:
> > merge_tables.r -p "*bz2" -o Escherichia-coli-202009.counts.csv
> > Command exit status: 126
> > Command output: (empty)
> > Command error: /bin/bash: /bin/bash: cannot execute binary file
> > 解决方法：修改了docker ENTRYPOINT 内容为：ENTRYPOINT ["/bin/bash", "-l", "-c"]
> > 2.解决上述报错之后，遇到了下面的问题：
> > [04/c9f19d] process > panphlanMap (C10_errfree_r0|Escherichia-coli-202009) [100%] 20 of 20 ✔ [e5/fd9c29] process > mergeProfile (Escherichia-coli-202009) [100%] 1 of 1, failed: 1 ✘ [- ] process > runStrainPanDAR - [- ] process > runMinPath - Execution cancelled -- Finishing pending tasks before exit WARN: Graphviz is required to render the execution DAG in the given format -- See http://www.graphviz.org for more info. Error executing process > 'mergeProfile (Escherichia-coli-202009)'
> > Caused by: Missing output file(s) `Escherichia-coli-202009.counts.csv` expected by process `mergeProfile (Escherichia-coli-202009)`
> > Command executed:
> > merge_tables.r -p "*bz2" -o Escherichia-coli-202009.counts.csv
> > Command exit status: 0
> > Command output: (empty)
> > Work dir: xxx/2.strainpanda/test/work/e5/fd9c2928b32e16382154eb3fb54db7
> > Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line
> 
> 首先，我很疑惑新的镜像居然也还是会有“/bin/bash: /bin/bash: cannot execute binary file”的问题。但是也很高兴你通过设置entrypoint似乎解决了。
> 
> 另外，我发现我们有个branch的更新，没有merge到main上面，也可能是导致问题的原因，所以您可能需要git update一下。
> 
> 如果还不行，再考虑检查下面的问题： 你的新问题显示，运行成功了，却没有结果。 我看不到更多的信息，只能有两方面猜测：
> 
> 1. 没有正确生成bz2文件。（这个您需要检查路径）
> 2. 实际上并没有正确运行。（这个您可能可以可以直接通过docker run进到镜像里面去实际操作，看看实际输出的情况）
> 
> 还是那句话，我没办法复现这个问题，所以一切都只能是猜测。

非常感谢能够这么及时的回复。
1. git update之后，还是有同样的报错。如下：

Launching `xxx/StrainPanDA-main/main.nf` [clever_shockley] DSL1 - revision: 4da4066d2b
executor >  local (21)
executor >  local (21)
executor >  local (21)
[f9/aa2de1] process > panphlanMap (C5_errfree_r0|Escherichia-coli-202009)  [100%] 20 of 20 ✔
[06/c2c9b7] process > mergeProfile (Escherichia-coli-202009)               [100%] 1 of 1, failed: 1 ✘
[-        ] process > runStrainPanDAR                                      -
[-        ] process > runMinPath                                           -
Execution cancelled -- Finishing pending tasks before exit
WARN: Graphviz is required to render the execution DAG in the given format -- See http://www.graphviz.org for more info.
Error executing process > 'mergeProfile (Escherichia-coli-202009)'

Caused by:
  Missing output file(s) `Escherichia-coli-202009.counts.csv` expected by process `mergeProfile (Escherichia-coli-202009)`

Command executed:

  Rscript /opt/bin/merge_tables.r -p "*bz2" -o Escherichia-coli-202009.counts.csv

Command exit status:
  0

Command output:
  (empty)

Work dir:
  xxxx/2.strainpanda/test/work/06/c2c9b7f9c49e27b2ba6661bc53e0c4

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

2. 我去Work dir下看了一下，bz2文件存在，其中部分内容如下：

GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:1117-2046     150
GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:2315-3916     150
GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:3946-5250     271
GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:8810-7236     450
GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:10151-13834   150
GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:16465-15776   450
GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:25260-25502   150
GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:32870-31980   150
GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:34429-32885   300
GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:38817-39737   150
GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:45729-43306   150
GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:46378-46986   231
GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:47059-48384   150
GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:55076-56155   26
GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:63439-63975   150
GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:64785-66371   150
GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:67792-69141   285
GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:69293-70942   150
GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:72388-71096   605
GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:74215-72566   150
GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:77077-78513   300
GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:88115-85968   600
GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:95346-93361   150
GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:96548-95619   150
GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:98218-97238   14
GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:99729-98197   450
GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:100791-99856  176
GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:101740-100850 300
GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:102099-102548 452
GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:111237-110512 150
GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:113972-113184 150
GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:115443-117671 150
GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:121589-120489 300
GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:123898-122255 148
GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:126237-125476 206
GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:128829-126562 300
GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:130219-131574 150
GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:137053-135713 150
GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:138343-137624 150
GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:139971-138340 149

_Originally posted by @wz115 in https://github.com/xbiome/StrainPanDA/issues/27#issuecomment-2134227214_

**Comment by yuxiangtan** [comment]
> ```
>           > > 是的，我的docker镜像没有安装成功。成功安装之后还是遇到了一些问题 1.如下报错信息（我认为我解决了这个问题）： [5b/e15e17] process > panphlanMap (Gutmock_R|Escherichia-coli-202009) [100%] 21 of 21 ✔ [97/688bf5] process > mergeProfile (Escherichia-coli-202009) [100%] 1 of 1, failed: 1 ✘ [- ] process > runStrainPanDAR - [- ] process > runMinPath - Execution cancelled -- Finishing pending tasks before exit WARN: Graphviz is required to render the execution DAG in the given format -- See http://www.graphviz.org for more info. Error executing process > 'mergeProfile (Escherichia-coli-202009)'
> ```
> 
> > > Caused by: Process `mergeProfile (Escherichia-coli-202009)` terminated with an error exit status (126)
> > > Command executed:
> > > merge_tables.r -p "*bz2" -o Escherichia-coli-202009.counts.csv
> > > Command exit status: 126
> > > Command output: (empty)
> > > Command error: /bin/bash: /bin/bash: cannot execute binary file
> > > 解决方法：修改了docker ENTRYPOINT 内容为：ENTRYPOINT ["/bin/bash", "-l", "-c"]
> > > 2.解决上述报错之后，遇到了下面的问题：
> > > [04/c9f19d] process > panphlanMap (C10_errfree_r0|Escherichia-coli-202009) [100%] 20 of 20 ✔ [e5/fd9c29] process > mergeProfile (Escherichia-coli-202009) [100%] 1 of 1, failed: 1 ✘ [- ] process > runStrainPanDAR - [- ] process > runMinPath - Execution cancelled -- Finishing pending tasks before exit WARN: Graphviz is required to render the execution DAG in the given format -- See http://www.graphviz.org for more info. Error executing process > 'mergeProfile (Escherichia-coli-202009)'
> > > Caused by: Missing output file(s) `Escherichia-coli-202009.counts.csv` expected by process `mergeProfile (Escherichia-coli-202009)`
> > > Command executed:
> > > merge_tables.r -p "*bz2" -o Escherichia-coli-202009.counts.csv
> > > Command exit status: 0
> > > Command output: (empty)
> > > Work dir: xxx/2.strainpanda/test/work/e5/fd9c2928b32e16382154eb3fb54db7
> > > Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line
> > 
> > 
> > 首先，我很疑惑新的镜像居然也还是会有“/bin/bash: /bin/bash: cannot execute binary file”的问题。但是也很高兴你通过设置entrypoint似乎解决了。
> > 另外，我发现我们有个branch的更新，没有merge到main上面，也可能是导致问题的原因，所以您可能需要git update一下。
> > 如果还不行，再考虑检查下面的问题： 你的新问题显示，运行成功了，却没有结果。 我看不到更多的信息，只能有两方面猜测：
> > 
> > 1. 没有正确生成bz2文件。（这个您需要检查路径）
> > 2. 实际上并没有正确运行。（这个您可能可以可以直接通过docker run进到镜像里面去实际操作，看看实际输出的情况）
> > 
> > 还是那句话，我没办法复现这个问题，所以一切都只能是猜测。
> 
> 非常感谢能够这么及时的回复。
> 
> 1. git update之后，还是有同样的报错。如下：
> 
> Launching `xxx/StrainPanDA-main/main.nf` [clever_shockley] DSL1 - revision: 4da4066d2b executor > local (21) executor > local (21) executor > local (21) [f9/aa2de1] process > panphlanMap (C5_errfree_r0|Escherichia-coli-202009) [100%] 20 of 20 ✔ [06/c2c9b7] process > mergeProfile (Escherichia-coli-202009) [100%] 1 of 1, failed: 1 ✘ [- ] process > runStrainPanDAR - [- ] process > runMinPath - Execution cancelled -- Finishing pending tasks before exit WARN: Graphviz is required to render the execution DAG in the given format -- See http://www.graphviz.org for more info. Error executing process > 'mergeProfile (Escherichia-coli-202009)'
> 
> Caused by: Missing output file(s) `Escherichia-coli-202009.counts.csv` expected by process `mergeProfile (Escherichia-coli-202009)`
> 
> Command executed:
> 
> Rscript /opt/bin/merge_tables.r -p "*bz2" -o Escherichia-coli-202009.counts.csv
> 
> Command exit status: 0
> 
> Command output: (empty)
> 
> Work dir: xxxx/2.strainpanda/test/work/06/c2c9b7f9c49e27b2ba6661bc53e0c4
> 
> Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`
> 
> 2. 我去Work dir下看了一下，bz2文件存在，其中部分内容如下：
> 
> GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:1117-2046 150 GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:2315-3916 150 GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:3946-5250 271 GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:8810-7236 450 GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:10151-13834 150 GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:16465-15776 450 GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:25260-25502 150 GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:32870-31980 150 GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:34429-32885 300 GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:38817-39737 150 GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:45729-43306 150 GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:46378-46986 231 GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:47059-48384 150 GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:55076-56155 26 GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:63439-63975 150 GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:64785-66371 150 GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:67792-69141 285 GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:69293-70942 150 GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:72388-71096 605 GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:74215-72566 150 GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:77077-78513 300 GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:88115-85968 600 GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:95346-93361 150 GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:96548-95619 150 GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:98218-97238 14 GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:99729-98197 450 GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:100791-99856 176 GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:101740-100850 300 GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:102099-102548 452 GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:111237-110512 150 GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:113972-113184 150 GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:115443-117671 150 GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:121589-120489 300 GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:123898-122255 148 GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:126237-125476 206 GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:128829-126562 300 GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:130219-131574 150 GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:137053-135713 150 GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:138343-137624 150 GCF_001900555.1_ASM190055v1_genomic:NZ_CP010125.1:139971-138340 149
> 
> _Originally posted by @wz115 in [#27 (comment)](https://github.com/xbiome/StrainPanDA/issues/27#issuecomment-2134227214)_

很抱歉，由于无法重现该错误，我们没有更多的办法去解决。

建议您参照下图手动完成merge（其实就一步）
![image](https://github.com/xbiome/StrainPanDA/assets/10011271/bb3ed04d-adab-4be0-aa0e-7b97edc27086)

然后参照下面的链接完成剩下的解构分析。
https://github.com/xbiome/StrainPanDA?tab=readme-ov-file#run-only-strainpandar-for-rerunning-strainpanda-with-modified-parameters

非常抱歉。

I'm sorry, but we were unable to reproduce the error, and we don't have additional solutions at this time.

Please follow the steps in the image below to manually complete the merge (it’s just one step).
![image](https://github.com/xbiome/StrainPanDA/assets/10011271/bb3ed04d-adab-4be0-aa0e-7b97edc27086)

Afterward, refer to the link below to finish the remaining structural analysis.
https://github.com/xbiome/StrainPanDA?tab=readme-ov-file#run-only-strainpandar-for-rerunning-strainpanda-with-modified-parameters

We apologize for the inconvenience.

**Comment by wz115** [comment]
按照您提供的方法，测试数据运行成功了。

**Comment by yuxiangtan** [comment]
> 按照您提供的方法，测试数据运行成功了。

好的，感谢反馈。很抱歉没法全流程完善。
