### ISSUE TITLE
5sample,8M reads on average, process runStrainPanDAR cost over 100GB memory 

### ISSUE THREAD

**Issue by fgnddddd** [xbiome/StrainPanDA#4]
Loading required package: rngtools
Loading required package: cluster
NMF - BioConductor layer [OK] | Shared memory capabilities [NO: synchronicity] | Cores 95/96
  To enable shared memory capabilities, try: install.extras('
NMF
')
Setting the maximum number of strains to 5 (number of samples)...
Timing stopped at: 6731 2.008e+04 336.5
Timing stopped at: 1.131e+04 3.429e+04 556.6
Timing stopped at: 1.72e+04 5.127e+04 736.1
Error in { :
  task 2 failed - "unable to find an inherited method for function 'scoef' for signature '"logical"'"
Calls: strain.decompose -> findNMFRank -> %do% -> <Anonymous>
In addition: Warning messages:
1: In cor(d.consensus, d.coph, method = "pearson") :
  the standard deviation is zero
2: In mclapply(argsList, FUN, mc.preschedule = preschedule, mc.set.seed = set.seed,  :
  scheduled cores 5, 6, 7, 9 did not deliver results, all values of the jobs will be affected
3: In mclapply(argsList, FUN, mc.preschedule = preschedule, mc.set.seed = set.seed,  :
  scheduled cores 3, 6, 8 did not deliver results, all values of the jobs will be affected
4: In mclapply(argsList, FUN, mc.preschedule = preschedule, mc.set.seed = set.seed,  :
  scheduled core 7 did not deliver a result, all values of the job will be affected
5: In (function (...)  :
  NAs were produced due to errors in some of the runs:
        -#3[r=3] -> (list) object cannot be coerced to type 'double' [in call to 'which.min']
        -#4[r=4] -> (list) object cannot be coerced to type 'double' [in call to 'which.min']
        -#5[r=5] -> (list) object cannot be coerced to type 'double' [in call to 'which.min']
Execution halted

**Comment by lch14forever** [comment]
Assuming this will be fixed by commit 49c6458
