### ISSUE TITLE
How to build a customized pangenome databases?

### ISSUE THREAD

**Issue by fgnddddd** [xbiome/StrainPanDA#5]
There is no link for downloading **Pre-built pangenome databases**

**Comment by hh1985** [comment]
Please document the building steps in README and prepare a script. @yuxiangtan

**Comment by yuxiangtan** [comment]
@lch14forever ，需要提供一下怎么增加注释

**Comment by lch14forever** [comment]
Use eggnog-mapper to replace usearch relying on KEGG database dump.
