### ISSUE TITLE
如果样品中没有发现--reflist 中的species，流程会运行出错

### ISSUE THREAD

**Issue by fgnddddd** [xbiome/StrainPanDA#7]

**Comment by hh1985** [comment]
Please specify a case to reproduce the error @fgnddddd

**Comment by fgnddddd** [comment]
不指定具体ref_list,默认使用所有 ref，以增加问题出现概率
命令：
`nextflow run /share/home/zhangzhikuan/zhangzhikuan_hpc/gitlab/xstrain/dev/main.nf -profile docker -bg --path /share/home/zhangzhikuan/zhangzhikuan_hpc/pipeline_test/xstrain/data --ref_path /share/work/runtime/databases/xstrain/panphlan_ref202009`

测试数据路径：
reads:  /share/home/zhangzhikuan/zhangzhikuan_hpc/pipeline_test/xstrain/data/
database:  /share/work/runtime/databases/xstrain/panphlan_ref202009

**Comment by fgnddddd** [comment]
**Error log:  Less than 5 samples left after preprocessing...**

Error executing process > 'runStrainPanDAR (Akkermansia-muciniphila-202009)'

Caused by:
  Process `runStrainPanDAR (Akkermansia-muciniphila-202009)` terminated with an error exit status (1)

Command executed:

  run_strainpandar.r Akkermansia-muciniphila-202009.counts.csv Akkermansia-muciniphila-202009 Akkermansia-muciniphila-202009.strainpanda 50

Command exit status:
  1

Command output:
  (empty)

Command error:
  Registered S3 methods overwritten by 'ggplot2':
    method         from
    [.quosures     rlang
    c.quosures     rlang
    print.quosures rlang

  Attaching package: 'dplyr'

  The following object is masked from 'package:Biobase':

      combine

  The following objects are masked from 'package:BiocGenerics':

      combine, intersect, setdiff, union

  The following objects are masked from 'package:stats':

      filter, lag

  The following objects are masked from 'package:base':

      intersect, setdiff, setequal, union

  Sample(s) filtered for the species: X7152
  Sample(s) filtered for the species: X7153
  Sample(s) filtered for the species: X7154
  Sample(s) filtered for the species: X7155
  Sample(s) filtered for the species: X7156

  Error: Less than 5 samples left after preprocessing...
  Execution halted

Work dir:
  /share/home/zhangzhikuan/zhangzhikuan_hpc/pipeline_test/xstrain/tmp/work/2d/c43cc241303fafa834e55874eb6e11

Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

Execution cancelled -- Finishing pending tasks before exit

**Comment by lch14forever** [comment]
Fixed by adding an error code (55) to StrainPanDAR's preprocessing checker. Error code 55 will be ignored by nextflow.
