### ISSUE TITLE
github 用户文档完善

### ISSUE THREAD

**Issue by hh1985** [xbiome/StrainPanDA#8]
We need to follow a template to start.

**Comment by hh1985** [comment]
PanPhlAn 3: https://github.com/SegataLab/panphlan/wiki/Home_3_0
DESMAN: https://github.com/chrisquince/DESMAN
InStrain: https://instrain.readthedocs.io/en/latest/

**Comment by hh1985** [comment]
宇翔的建议：
整理github上的guide：有没有什么对标的？（PanPhlAn）【相对不急】
    1. 主页的指引太少，也不清晰，没有把整个体系说清楚。
        * 装strainpanda.r的R依赖，写清楚了，但是没突出
    2. docker的比较清晰，但是如果更新了以后，如何更新？重新build？下载?
        * 貌似现在重新build容易出问题？
    3. 当前没有任何和结果解读相关的信息。
    4. 补充我们文章的案例
        * 可以加在example分文件夹
        * 我和陈浩分别负责自己的案例？
    5. 单独strainpanda本身的部分现在是在src里面，的确可以搞一个单独的页面，不用都堆一起。但是也不应该是当前这样直接在R里跑的，意义不大。应该是搞成整个Rscript相关的运行，然后结果的解释之类的。
        * 目前提供rds的话，还需要补充一下rds怎么使用

**Comment by yuxiangtan** [comment]
6. 补充建参考数据库部分（包括怎么下载，以及怎么自建+注释） - 宇翔负责

**Comment by hh1985** [comment]
> 6. 补充建参考数据库部分（包括怎么下载，以及怎么自建+注释） - 宇翔负责

See #5

**Comment by hh1985** [comment]
> 4. 补充我们文章的案例
> 可以加在example分文件夹
> 我和陈浩分别负责自己的案例？

See #13 @lch14forever  @yuxiangtan

**Comment by hh1985** [comment]
> 3. 当前没有任何和结果解读相关的信息。

See #14 @lch14forever

**Comment by hh1985** [comment]
> 2. docker的比较清晰，但是如果更新了以后，如何更新？重新build？下载?
> 貌似现在重新build容易出问题？

See #15 @hh1985

**Comment by hh1985** [comment]
> 5. 单独strainpanda本身的部分现在是在src里面，的确可以搞一个单独的页面，不用都堆一起。但是也不应该是当前这样直接在R里跑的，意义不大。应该是搞成整个Rscript相关的运行，然后结果的解释之类的。
> * 目前提供rds的话，还需要补充一下rds怎么使用

See #16 @lch14forever

**Comment by hh1985** [comment]
> 1. 主页的指引太少，也不清晰，没有把整个体系说清楚。
> * 装strainpanda.r的R依赖，写清楚了，但是没突出

@yuxiangtan  Yuxiang can add more comments regarding the page layout.

**Comment by lch14forever** [comment]
> > 3. 当前没有任何和结果解读相关的信息。
> 
> See #14 @lch14forever

Fixed

**Comment by lch14forever** [comment]
> #15

Fixed

**Comment by lch14forever** [comment]
> > 5. 单独strainpanda本身的部分现在是在src里面，的确可以搞一个单独的页面，不用都堆一起。但是也不应该是当前这样直接在R里跑的，意义不大。应该是搞成整个Rscript相关的运行，然后结果的解释之类的。
> > 
> > 
> > * 目前提供rds的话，还需要补充一下rds怎么使用
> 
> See #16 @lch14forever

Consider fixed: https://github.com/xbiome/StrainPanDA#run-strainpandar

**Comment by lch14forever** [comment]
> > 1. 主页的指引太少，也不清晰，没有把整个体系说清楚。
> > 
> > 
> > * 装strainpanda.r的R依赖，写清楚了，但是没突出
> 
> @yuxiangtan Yuxiang can add more comments regarding the page layout.

Consider fixed: https://github.com/xbiome/StrainPanDA#local-installation
