### ISSUE TITLE
runStrainpanda 默认内存8G, 随着自动增加内存功能未生效

### ISSUE THREAD

**Issue by fgnddddd** [xbiome/StrainPanDA#9]
nextflow 中当process运行出错后设置有自动重新提交任务，其内存随着重试次数递加，实际使用过程中该功能未生效

参数为：-profile docker的情况 ，docker的内存会被限制到设定的值, 运行时会触发OOM。

`nextflow run /share/home/zhangzhikuan/zhangzhikuan_hpc/gitlab/xstrain/dev/main.nf -profile docker -bg --path /share/home/zhangzhikuan/zhangzhikuan_hpc/pipeline_test/xstrain/data --ref_path /share/work/runtime/databases/xstrain/panphlan_ref202009 --ref_list /share/home/zhangzhikuan/zhangzhikuan_hpc/pipeline_test/xstrain/ref_list`

**Comment by hh1985** [comment]
@fgnddddd 这个issue是否已经解决了呢？

**Comment by fgnddddd** [comment]
这个问题仅存在于使用docker的情况下，一旦出现OOM导致的错误，并不会自动retry，这应该和nextflow的retry策略设置有关，需要对nextflow代码进行一些修改才可以解决

这个问题并不是一个非常严重的问题。
提出这个问题是因为看到代码中设置有内存自动增加的功能，但实际上未起作用，属于一个小bug

**Comment by fgnddddd** [comment]
![image](https://user-images.githubusercontent.com/99473225/167089538-b3cd90cd-a171-4205-8796-155348c3d016.png)
图中runStrainpandar 峰值内存可以达到50GB,所以对于计算资源比较富足的用户来说，自动retry增加内存还是有一定需求的

**Comment by hh1985** [comment]
This can be a low priority issue.

**Comment by fgnddddd** [comment]
NMF再被限制内存后并不会直接OOM，而是自行终止程序
exit code 为 1

**Comment by lch14forever** [comment]
Not sure how to handle this.
Will this work?

```nextflow
errorStrategy = { task.exitStatus in [55] ? 'ignore' : (  task.exitStatus in [143,137,104,134,139,1] ? 'retry': 'finish') }
```

**Comment by fgnddddd** [comment]
> Not sure how to handle this. Will this work?
> 
> ```nextflow
> errorStrategy = { task.exitStatus in [55] ? 'ignore' : (  task.exitStatus in [143,137,104,134,139,1] ? 'retry': 'finish') }
> ```

Unfortunately,It didn't work.
Use a function to parse the exit_code might be useful, just like the function "check_max"

**Comment by fgnddddd** [comment]
也许可以这样实现
```
errorStrategy = { 
    if(task.exitStatus in [55]) return 'ignore'
    if(task.exitStatus in [143,137,104,134,139,1]) return  'retry'
    return 'finish'
}
```
@lch14forever

**Comment by lch14forever** [comment]
Fixed as suggested.
